name: 'PR Coverage Annotations'
description: 'Annotate pull requests with uncovered code—highlights changed lines not covered by tests using LCOV reports'
inputs:
  token:
    description: 'GitHub Token to access the Repo'
    required: true
  coverage-info-path:
    description: 'Path to the LCOV Info file'
    default: './coverage/lcov.info'
    required: false
  total-coverage-files:
    description: 'Total Number of Coverage Files to process'
    default: 1
    required: false
  action-type:
    description: 'The WorkFlow Event that invoked this Action'
    default: 'pull request'
    required: false
  annotation-coverage:
    description: 'if Coverage Annotations should be on top of each file or in-line'
    default: 'summarize' # or detailed
    required: false
  annotation-type:
    description: 'Aspects of the Coverage Report to Annotate'
    default: 'all' # or line/function/branch
    required: false

runs:
  using: 'node20'
  main: 'index.js'
