name: 'PR Coverage Annotations'
description: 'Annotate pull requests with uncovered code—highlights changed lines not covered by tests using LCOV reports'
inputs:
  token:
    description: 'GitHub Token to access the Repo'
    required: true
  coverage-info-path:
    description: 'Path to the LCOV Info file'
    default: './coverage/lcov.info'
    required: false
  total-coverage-files:
    description: 'Total Number of Coverage Files to process'
    default: '1'
    required: false
  action-type:
    description: 'The WorkFlow Event that invoked this Action'
    default: 'pull request'
    required: false
  annotation-coverage:
    description: 'if Coverage Annotations should be on top of each file or in-line'
    default: 'summarize' # or detailed
    required: false
  annotation-type:
    description: 'Aspects of the Coverage Report to Annotate'
    default: 'all' # or line/function/branch
    required: false
  new-lines-coverage-threshold:
    description: 'Minimum percentage of new/changed lines that must be covered by tests (0-100). Check fails if below this threshold.'
    default: '90'
    required: false
  comment-on-pr:
    description: "Post a coverage summary comment on the PR. Set to 'false' if you get 403 (e.g. PRs from forks with GITHUB_TOKEN)."
    default: 'true'
    required: false
  coverage-files-include:
    description: "Optional. Comma-separated include patterns. Supported: extension (.ts,.tsx), glob (*.js), path segment (src/), or **/path/**. Only files matching one of these count toward coverage."
    required: false
  coverage-files-exclude:
    description: "Optional. Comma-separated exclude patterns (same format as include). Files matching any of these are excluded from coverage stats."
    required: false
  debug:
    description: "Set to 'true' to log coverage debug: which files were considered/ignored and how each uncovered line contributes to the coverage percentage."
    default: 'false'
    required: false

runs:
  using: 'node24'
  main: 'dist/index.js'
